version: "2"

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"
  apt_packages:
    - plantuml
    - graphviz
  jobs:
      pre_build:
        - cd software/bmi
        - pip install -r requirements.txt
        - pytest --junitxml=report.xml

python:
  install:
    - requirements: docs/requirements.txt

sphinx:
  configuration: docs/source/conf.py

formats:
  - pdf
  - epub
