version: "2"

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"
    nodejs: "16"
  apt_packages:
    - plantuml
    - graphviz
  jobs:
      post_install:
        - npm install -g @mermaid-js/mermaid-cli
      pre_build:
        - cd software/bmi && pip install -r requirements.txt && pytest --junitxml=report.xml || true

python:
  install:
    - requirements: docs/requirements.txt

sphinx:
  configuration: docs/source/conf.py

formats:
  - pdf
