name: Build Documentation

on:
  pull_request:

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checking out
      uses: actions/checkout@v1

    - name: Install Python packages
      run: |
        python3 -m pip install --upgrade pip
        pip install -r docs/requirements.txt

    - name: Install Graphviz and LaTeX packages
      run: |
        sudo apt-get update -y
        sudo apt-get install -y graphviz
        sudo apt-get install -y latexmk texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended

    - name: Build LaTeX documentation
      run: |
        cd docs
        make latexpdf

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: req-mgmt.pdf
        path: docs/build/latex/req-mgmt.pdf